apiVersion: batch/v1
kind: Job
metadata:
  name: cpd-install-v53x
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: cpd-install
    spec:
      containers:
      - name: olm-utils-v4
        envFrom:
        - configMapRef:
            name: cpd-vars
        env:
        - name: OCP_TOKEN
          valueFrom:
            secretKeyRef:
              name: cpd-token
              key: token
        imagePullPolicy: Always
        image: ${IMAGE_PULL_PREFIX}/cpopen/cpd/olm-utils-v4@sha256:4d55bcf934f282031d786d29c9468efb042b7a98a0cddd1887eb397b1ad6bb20
        command: ["/bin/sh", "-c"]
        args: 
          - "/opt/ansible/cpd_install.sh"
        volumeMounts:
          - name: olm-utils-storage
            mountPath: /tmp/work
          - name: cpd-install-options
            mountPath: /tmp/work/install-options.yml
            subPath: install-options.yml
          - name: cpd-install-options
            mountPath: /opt/ansible/cpd_install.sh
            subPath: cpd_install.sh
      restartPolicy: Never
      serviceAccount: cpd-silent-install
      volumes:
        - name: olm-utils-storage
          persistentVolumeClaim:
            claimName: olm-utils-storage
        - name: cpd-install-options
          configMap:
            defaultMode: 0755
            name: cpd-install-options
      securityContext:
        fsGroup: 0
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
