apiVersion: v1
kind: Pod
metadata:
  name: cpd-install-v53x
  labels:
    app: cpd-install
spec:
  containers:
  - name: olm-utils-v4
    envFrom:
    - configMapRef:
        name: cpd-vars
    env:
    - name: OCP_TOKEN
      valueFrom:
        secretKeyRef:
          name: cpd-token
          key: token
    imagePullPolicy: Always
    image: ${IMAGE_PULL_PREFIX}/cpopen/cpd/olm-utils-v4@sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827
    command: ["/bin/sh", "-c"]
    args: 
      - "/opt/ansible/cpd_install.sh"
    volumeMounts:
      - name: olm-utils-storage
        mountPath: /tmp/work
      - name: cpd-install-options
        mountPath: /tmp/work/install-options.yml
        subPath: install-options.yml
      - name: cpd-install-options
        mountPath: /opt/ansible/cpd_install.sh
        subPath: cpd_install.sh
  restartPolicy: Never
  serviceAccount: cpd-silent-install
  volumes:
    - name: olm-utils-storage
      persistentVolumeClaim:
        claimName: olm-utils-storage
    - name: cpd-install-options
      configMap:
        defaultMode: 0755
        name: cpd-install-options
  securityContext:
    fsGroup: 0
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
