apiVersion: v1
kind: ConfigMap
metadata:
  name: cpd-vars
  namespace: ${PROJECT_CPD_INST_OPERANDS}
data:
  PRIVATE_REGISTRY_USER: ${PRIVATE_REGISTRY_USER}
  PRIVATE_REGISTRY_PASSWORD: ${PRIVATE_REGISTRY_PASSWORD}
  IBM_ENTITLEMENT_KEY: "${IBM_ENTITLEMENT_KEY}"
  PROJECT_LICENSE_SERVICE: "${PROJECT_LICENSE_SERVICE}"
  PROJECT_SCHEDULING_SERVICE: "${PROJECT_SCHEDULING_SERVICE}"
  PROJECT_CPD_INST_OPERATORS: "${PROJECT_CPD_INST_OPERATORS}"
  PROJECT_CPD_INST_OPERANDS: "${PROJECT_CPD_INST_OPERANDS}"
  OPENSHIFT_TYPE: "self-managed"
  COMPONENTS: "${COMPONENTS}"
  ENTITLEMENT_PRODUCTION: "${ENTITLEMENT_PRODUCTION}"
  ENTITLEMENT: "${ENTITLEMENT}"
  VERSION: "5.3.1"
  IMAGE_ARCH: "amd64"
  STG_CLASS_BLOCK: "${STG_CLASS_BLOCK}"
  STG_CLASS_FILE: "${STG_CLASS_FILE}"
  OCP_URL: "kubernetes.default.svc.cluster.local"
  IMAGE_PULL_SECRET: "ibm-entitlement-key"
  IMAGE_PULL_PREFIX: "${IMAGE_PULL_PREFIX}"
  OLM_UTILS_IMAGE: "${IMAGE_PULL_PREFIX}/cpopen/cpd/olm-utils-v4@sha256:3f03ae78e4101a63c089980ffb5eef0db51b8897afd44b609ce409897e5f0827"
  