apiVersion: v1
kind: ConfigMap
metadata:
  name: cpd-install-options
data:
  install-options.yml: |
    ################################################################################
    # IBM Knowledge Catalog parameters
    ################################################################################
    non_olm:
      wkc:
        enableKnowledgeGraph: True
        useFDB: True
        enableDataQuality: True
  cpd_shared.sh: |
    #!/bin/bash
    set -ex
    cat case.* > /tmp/work/case.tar.gz
    tar -C /tmp/work -zxf /tmp/work/case.tar.gz
    ################################################################################
    # Login to OCP
    ################################################################################
    login-to-ocp --token=${OCP_TOKEN} --server=${OCP_URL}
    ################################################################################
    # Process LimitRanges, NetworkPolicy and Quotas
    ################################################################################
    oc get cm cpd-silent-limitranges -o jsonpath='{.data.limitranges}' | tee > /tmp/work/limitranges.yaml
    [ -s "/tmp/work/limitranges.yaml" ] && oc create -f /tmp/work/limitranges.yaml
    oc get cm cpd-silent-networkpolicy -o jsonpath='{.data.networkpolicy}' | tee > /tmp/work/networkpolicy.yaml
    [ -s "/tmp/work/networkpolicy.yaml" ] && oc create -f /tmp/work/networkpolicy.yaml
    oc get cm cpd-silent-quotas -o jsonpath='{.data.quotas}' | tee > /tmp/work/resourcequota.yaml
    [ -s "/tmp/work/resourcequota.yaml" ] && oc create -f /tmp/work/resourcequota.yaml
    ################################################################################
    # Install License Manager and Scheduler
    ################################################################################
    apply-cluster-components --release=${VERSION} --license_acceptance=true --licensing_ns=${PROJECT_LICENSE_SERVICE}
    case-download --components=scheduler --release=${VERSION} --scheduler_ns=${PROJECT_SCHEDULING_SERVICE} --cluster_resources=true
    oc apply -f /tmp/work/cluster_scoped_resources.yaml --server-side --force-conflicts | tee /tmp/work/scheduler-cluster_scoped_resources.out
    mv /tmp/work/cluster_scoped_resources.yaml /tmp/work/scheduler-cluster_scoped_resources.yaml
    kubectl get secret -n openshift-config pull-secret -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d > /tmp/work/dockerconfig.json
    oc create secret docker-registry ${IMAGE_PULL_SECRET} --from-file ".dockerconfigjson=/tmp/work/dockerconfig.json" --namespace=${PROJECT_SCHEDULING_SERVICE}
    oc create secret docker-registry ${IMAGE_PULL_SECRET} --from-file ".dockerconfigjson=/tmp/work/dockerconfig.json" --namespace=${PROJECT_CPD_INST_OPERATORS}
    oc create secret docker-registry ${IMAGE_PULL_SECRET} --from-file ".dockerconfigjson=/tmp/work/dockerconfig.json" --namespace=${PROJECT_CPD_INST_OPERANDS}
    apply-scheduler --release=${VERSION} --license_acceptance=true --scheduler_ns=${PROJECT_SCHEDULING_SERVICE} --image_pull_prefix=${IMAGE_PULL_PREFIX} --image_pull_secret=${IMAGE_PULL_SECRET}
  cpd_install.sh: |
    #!/bin/bash
    set -ex
    ################################################################################
    # Login to OCP
    ################################################################################
    login-to-ocp --token=${OCP_TOKEN} --server=${OCP_URL}
    ################################################################################
    # Install Cloud Pak for Data
    ################################################################################
    case-download --components=${COMPONENTS} --release=${VERSION} --operator_ns=${PROJECT_CPD_INST_OPERATORS} --cluster_resources=true
    oc apply -f /tmp/work/cluster_scoped_resources.yaml --server-side --force-conflicts | tee /tmp/work/cluster_scoped_resources.out
    authorize-instance-topology --cpd_operator_ns=${PROJECT_CPD_INST_OPERATORS} --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS}
    install-components --license_acceptance=true --components=${COMPONENTS} --release=${VERSION} --operator_ns=${PROJECT_CPD_INST_OPERATORS} --instance_ns=${PROJECT_CPD_INST_OPERANDS} --block_storage_class=${STG_CLASS_BLOCK} --file_storage_class=${STG_CLASS_FILE} --image_pull_prefix=${IMAGE_PULL_PREFIX} --image_pull_secret=${IMAGE_PULL_SECRET} --param-file=/tmp/work/install-options.yml
    apply-entitlement --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS} --entitlement=${ENTITLEMENT:-cpd-enterprise} --production=${ENTITLEMENT_PRODUCTION:-false}
    get-cpd-instance-details --cpd_instance_ns=${PROJECT_CPD_INST_OPERANDS} --get_admin_initial_credentials=true
