apiVersion: v1
kind: ConfigMap
metadata:
  name: cpd-vars
  namespace: ${PROJECT_CPD_INST_OPERANDS}
data:
  PROJECT_LICENSE_SERVICE: "${PROJECT_LICENSE_SERVICE}"
  PROJECT_SCHEDULING_SERVICE: "${PROJECT_SCHEDULING_SERVICE}"
  PROJECT_CPD_INST_OPERATORS: "${PROJECT_CPD_INST_OPERATORS}"
  PROJECT_CPD_INST_OPERANDS: "${PROJECT_CPD_INST_OPERANDS}"
  OPENSHIFT_TYPE: "self-managed"
  IBM_ENTITLEMENT_KEY: "<your entitlement key>"
  COMPONENTS: "cpd_platform,factsheet,analyticsengine,datarefinery,datastage_ent,dmc,wkc,ws_pipelines,wml,openscale,ws,hee"
  VERSION: "5.3.0"
  IMAGE_ARCH: "amd64"
  STG_CLASS_BLOCK: "managed-block-storage"
  STG_CLASS_FILE: "managed-nfs-storage"
  OCP_URL: "kubernetes.default.svc.cluster.local"
  IMAGE_PULL_SECRET: "ibm-entitlement-key"
  IMAGE_PULL_PREFIX: "artifactory.gym.lan/docker"
  OLM_UTILS_IMAGE: "icr.io/cpopen/cpd/olm-utils-v4@sha256:8609fc7f1acb037aac0d6081b4d49552a417eafb63f1d640ba653c54c1985e7b"
  
