---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpd-silent-install-licensemanager-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpd-licensemanager-list
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpd-silent-install-ibmlicensings-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibmlicensings.operator.ibm.com-v1alpha1-view
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpd-silent-install-olm-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-olm-view
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-silent-install-admin
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-silent-install-admin
  namespace: ${PROJECT_CPD_INST_OPERANDS}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-silent-install-admin
  namespace: ${PROJECT_CPD_INST_OPERATORS}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-silent-install-admin
  namespace: ${PROJECT_LICENSE_SERVICE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-silent-install-admin
  namespace: ${PROJECT_SCHEDULING_SERVICE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: cpd-silent-install
    namespace: ${PROJECT_CPD_INST_OPERANDS}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-instance-admin-apply-olm-rbac
  namespace: ${PROJECT_CPD_INST_OPERATORS}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cpd-instance-admin-apply-olm
subjects:
- kind: ServiceAccount
  name: cpd-silent-install
  namespace: ${PROJECT_CPD_INST_OPERANDS}