apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: olm-utils-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: ${STG_CLASS_FILE}
